---
- gather_facts: false
  hosts: localhost
  tasks:
  - name: Create a ticket in SNOW updated
    register: new_change_request
    snow_record:
      data:
        assignment_group: Application Development
        category: Software
        short_description: 'kartik'
        type: Normal
      instance: dev57831
      password: Swiftdzire@0587
      state: present
      table: change_request
      username: admin
    register: new_change_request
  - debug: var=new_change_request.record.number